name: aoc
version: 1.0.0

environment:
  sdk: ^3.10.0

dependencies:
  collection: ^1.19.1
  equatable: ^2.0.7
  meta: ^1.17.0
  quiver: ^3.2.2
  timing: ^1.0.2
  trotter: ^2.2.2

dev_dependencies:
  benchmark_harness: ^2.4.0
  test: ^1.28.0
  very_good_analysis: ^10.0.0
